//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaberTbl
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string spot { get; set; }
        public string content { get; set; }
        public Nullable<int> EditorId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Editor Editor { get; set; }
        public virtual Image Image { get; set; }
    }
}
