//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjeHaberDbEntities : DbContext
    {
        public ProjeHaberDbEntities()
            : base("name=ProjeHaberDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Editor> Editor { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<HaberTbl> HaberTbl { get; set; }
    }
}
